### ISSUE TITLE
Error in frame[, "cluster"] : subscript out of bounds

### ISSUE THREAD

**Issue by PaniGopaluni** [tchitchek-lab/SPADEVizR#3]
I am trying to read cluster FCS files, created using SPADE3.0 software (Peng Qui) in SPADEVizR. However, I am repeatedly getting Error in frame[,"cluster'): subscript out of bounds error. I would appreciate it if you could let me know how to resolve this issue? Thanks,

**Comment by nicolas-tchitchek** [comment]
Dear PaniGopaluni,
Thank you for your interest in the SPADEVizR package.
Could you please detail and provide the R code that you are using to import your SPADE results?
In principle, you should use the ‘importResultsFromSPADE’ function but the error that you get seems to be associated to another import function. 
Thank you and best regards,
Nicolas

**Comment by PaniGopaluni** [comment]
Dear Nicolas,

Thanks for your prompt response.
I have used Peng Qui SPADE3.0 software (Matlab version) to create clustering FCS files. The folder has 2 FCS files from two samples. Then I am using the below function:

results <- importResultsFromFCS("20181220/exported_results/clustering_result_added_in_fcs/“)

This is the error message


[START] - importing clustering results from FCS file
clustering_result_added_in_fcs

FCS files loading:
	archsin transform...
	compute quantiles bounds...
	extract results from FCS files...
Error in frame[, "cluster"] : subscript out of bounds
In addition: Warning message:
In exclude.markers(flowset, exclude.markers, colnames.FCS = flowset@colnames) :
  Unknown marker to exclude: cell_length, FileNum, density

I have not used importResultsFromSPADE as the output is mainly .mat files. I am attaching a screenshot of the files generated by the program



Thanks for your help,

Regards,
Pani





Dr Pani Gopaluni
Research fellow
Department of Medicine
University of Cambridge
Cambridge
sg743@cam.ac.uk

**Comment by nicolas-tchitchek** [comment]
Dear Pani,

Thank you for these details.

In fact, the mat files that you are referring to do not contain an additional column specifying the cluster associated to each cell. This reason explains why you get this error. These mat files that you are referring to seem just to correspond to extracted input FCS files in a MATLAB format.

After investigations on the SPADE 3.0 software, we have identified that the cell-cluster associations are available in another file generated in the working directory by the SPADE 3.0 algorithm.
Our SPADEVizR package was designed to work with SPADE results generated by the R SPADE package (https://github.com/nolanlab/spade), but not with this MATLAB version of SPADE.

We will make a new import function for the results generated by the MATLAB version in the near future, but I suggest you to use the R SPADE package meanwhile.

If you really need to use the SPADE 3.0 software and this MATLAB version, you should be able to add a “cluster” column to your FCS files or text files based on the different result files generated (while we add this new import feature using a proper function).

Please do not hesitate if you have further questions or remarks,

Best,

Nicolas

**Comment by PaniGopaluni** [comment]
Dear Nicolas,

Thanks for your prompt response. I will use the Spade function in R.

Thanks 
Pani
